links:
  flipkart_url: https://www.flipkart.com/search?q=
  product_url: https://www.flipkart.com

secrets:
  mongodb: mongodb+srv://root:root@flipkartstore.gdjqe04.mongodb.net/?retryWrites=true&w=majority